### ISSUE TITLE
书本的图片刊印问题

### ISSUE THREAD

**Issue by huangjd3** [waylau/distributed-systems-technologies-and-cases-analysis#16]
请问实体书的图是黑白的吗？我从链接买了这本书，但是看到图片黑白而且相对而言不是很清晰，不太确定是否是正版

**Comment by waylau** [comment]
@huangjd3 

你好，实体书的插图都是黑白的。
请问是从哪里买的呢？正规的网店应该都是正版的，如果觉得有疑问，请咨询卖家。

另外，可以截图放上来看下，是书中哪些图片不清晰呢？
